var stepSum =[
        {
            "summaryId": "x34f8618-61363b00-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630944000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61363e84-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630944900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61364208-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630945800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136458c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630946700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61364910-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630947600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61364c94-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630948500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61365018-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 30,
            "distanceInMeters": 21.36,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630949400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61365018-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630949400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136539c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630950300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61365720-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630951200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61365aa4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630952100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61365e28-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630953000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613661ac-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630953900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61366530-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630954800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613668b4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630955700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61366c38-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630956600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61366fbc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630957500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61367340-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630958400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613676c4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630959300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61367a48-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630960200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61367dcc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630961100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61368150-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630962000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613684d4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630962900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61368858-6",
            "activityType": "WALKING",
            "activeKilocalories": 4,
            "steps": 119,
            "distanceInMeters": 84.73,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 300,
            "startTimeInSeconds": 1630963800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.8827194,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.2,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61368858-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630963800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61368858-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 600,
            "startTimeInSeconds": 1630963800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 7.0
        },
        {
            "summaryId": "x34f8618-61368bdc-6",
            "activityType": "WALKING",
            "activeKilocalories": 3,
            "steps": 203,
            "distanceInMeters": 144.53,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 420,
            "startTimeInSeconds": 1630964700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.4728854,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.4285714285714284,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61368bdc-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630964700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61368bdc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1630964700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61368f60-6",
            "activityType": "WALKING",
            "activeKilocalories": 4,
            "steps": 339,
            "distanceInMeters": 241.37,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 300,
            "startTimeInSeconds": 1630965600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.8827194,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.6,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61368f60-0",
            "activityType": "GENERIC",
            "activeKilocalories": 3,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630965600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61368f60-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 600,
            "startTimeInSeconds": 1630965600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613692e4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630966500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61369668-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630967400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61369668-6",
            "activityType": "WALKING",
            "activeKilocalories": 1,
            "steps": 74,
            "distanceInMeters": 52.69,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630967400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.5516996,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613699ec-6",
            "activityType": "WALKING",
            "activeKilocalories": 24,
            "steps": 1066,
            "distanceInMeters": 758.99,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1630968300,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.2067988,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613699ec-0",
            "activityType": "GENERIC",
            "activeKilocalories": 6,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630968300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61369d70-6",
            "activityType": "WALKING",
            "activeKilocalories": 7,
            "steps": 636,
            "distanceInMeters": 452.83,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1630969200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.6436496,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.3333333333333335,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61369d70-0",
            "activityType": "GENERIC",
            "activeKilocalories": 2,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630969200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61369d70-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1630969200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136a0f4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630970100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136a478-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 98,
            "distanceInMeters": 69.78,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630971000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136a478-0",
            "activityType": "GENERIC",
            "activeKilocalories": 14,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630971000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136a478-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630971000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136a7fc-6",
            "activityType": "WALKING",
            "activeKilocalories": 5,
            "steps": 396,
            "distanceInMeters": 281.95,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1630971900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.6896245,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.125,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136a7fc-0",
            "activityType": "GENERIC",
            "activeKilocalories": 3,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630971900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136a7fc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 420,
            "startTimeInSeconds": 1630971900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-6136ab80-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 23,
            "distanceInMeters": 16.38,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630972800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 4.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136ab80-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630972800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136af04-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 11,
            "distanceInMeters": 7.83,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630973700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136af04-0",
            "activityType": "GENERIC",
            "activeKilocalories": 4,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630973700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136af04-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1630973700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136b288-6",
            "activityType": "WALKING",
            "activeKilocalories": 2,
            "steps": 133,
            "distanceInMeters": 94.69,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 257,
            "startTimeInSeconds": 1630974600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.515206,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136b288-0",
            "activityType": "GENERIC",
            "activeKilocalories": 3,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630974600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136b288-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 643,
            "startTimeInSeconds": 1630974600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136b60c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630975500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136b990-6",
            "activityType": "WALKING",
            "activeKilocalories": 1,
            "steps": 32,
            "distanceInMeters": 22.79,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 75,
            "startTimeInSeconds": 1630976400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.8827194,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.4,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136b990-0",
            "activityType": "GENERIC",
            "activeKilocalories": 7,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630976400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136b990-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 825,
            "startTimeInSeconds": 1630976400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-6136bd14-1",
            "activityType": "RUNNING",
            "activeKilocalories": 0,
            "steps": 18,
            "distanceInMeters": 19.22,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 15,
            "startTimeInSeconds": 1630977300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136bd14-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 63,
            "distanceInMeters": 44.85,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630977300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.5,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136bd14-0",
            "activityType": "GENERIC",
            "activeKilocalories": 11,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630977300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136bd14-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 825,
            "startTimeInSeconds": 1630977300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-6136c098-0",
            "activityType": "GENERIC",
            "activeKilocalories": 7,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630978200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136c098-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630978200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136c41c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630979100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136c7a0-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 42,
            "distanceInMeters": 29.91,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 45,
            "startTimeInSeconds": 1630980000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136c7a0-0",
            "activityType": "GENERIC",
            "activeKilocalories": 6,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630980000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136c7a0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 855,
            "startTimeInSeconds": 1630980000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136cb24-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 50,
            "distanceInMeters": 35.6,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630980900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.75,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136cb24-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630980900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136cb24-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1630980900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136cea8-6",
            "activityType": "WALKING",
            "activeKilocalories": 3,
            "steps": 23,
            "distanceInMeters": 16.37,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630981800,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.6550992,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.0,
            "maxMotionIntensity": 1.0
        },
        {
            "summaryId": "x34f8618-6136cea8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630981800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136d22c-6",
            "activityType": "WALKING",
            "activeKilocalories": 4,
            "steps": 410,
            "distanceInMeters": 291.92,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 310,
            "startTimeInSeconds": 1630982700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.8542447,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.096774193548387,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136d22c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 590,
            "startTimeInSeconds": 1630982700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136d5b0-6",
            "activityType": "WALKING",
            "activeKilocalories": 13,
            "steps": 606,
            "distanceInMeters": 431.47,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1630983600,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.1953492,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.3333333333333335,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136d5b0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1630983600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136d934-6",
            "activityType": "WALKING",
            "activeKilocalories": 10,
            "steps": 891,
            "distanceInMeters": 634.39,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630984500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.8487688,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.3076923076923075,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136d934-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630984500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136dcb8-6",
            "activityType": "WALKING",
            "activeKilocalories": 2,
            "steps": 66,
            "distanceInMeters": 47.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 240,
            "startTimeInSeconds": 1630985400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.5516996,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.5,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136dcb8-0",
            "activityType": "GENERIC",
            "activeKilocalories": 3,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630985400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136dcb8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 660,
            "startTimeInSeconds": 1630985400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136e03c-6",
            "activityType": "WALKING",
            "activeKilocalories": 1,
            "steps": 34,
            "distanceInMeters": 24.2,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630986300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.5516996,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136e03c-0",
            "activityType": "GENERIC",
            "activeKilocalories": 2,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630986300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136e03c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630986300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136e3c0-6",
            "activityType": "WALKING",
            "activeKilocalories": 2,
            "steps": 23,
            "distanceInMeters": 16.38,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 240,
            "startTimeInSeconds": 1630987200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.5516996,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.5,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136e3c0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 660,
            "startTimeInSeconds": 1630987200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136e744-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 95,
            "distanceInMeters": 67.64,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1630988100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136e744-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630988100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136e744-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1630988100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136eac8-6",
            "activityType": "WALKING",
            "activeKilocalories": 1,
            "steps": 154,
            "distanceInMeters": 109.65,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1630989000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.5516996,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136eac8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1630989000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136ee4c-6",
            "activityType": "WALKING",
            "activeKilocalories": 5,
            "steps": 432,
            "distanceInMeters": 307.55,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 420,
            "startTimeInSeconds": 1630989900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.7881423,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.142857142857143,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136ee4c-0",
            "activityType": "GENERIC",
            "activeKilocalories": 6,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630989900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6136ee4c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1630989900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136f1d0-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 13,
            "distanceInMeters": 9.25,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630990800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6136f1d0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1630990800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136f554-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 13,
            "distanceInMeters": 9.26,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630991700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6136f554-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1630991700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136f8d8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630992600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136fc5c-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 118,
            "distanceInMeters": 84.02,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 240,
            "startTimeInSeconds": 1630993500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.25,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6136fc5c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.01,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 660,
            "startTimeInSeconds": 1630993500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6136ffe0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630994400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61370364-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630995300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613706e8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630996200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61370a6c-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 41,
            "distanceInMeters": 29.19,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 105,
            "startTimeInSeconds": 1630997100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61370a6c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 795,
            "startTimeInSeconds": 1630997100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61370df0-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 76,
            "distanceInMeters": 54.11,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 90,
            "startTimeInSeconds": 1630998000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-61370df0-0",
            "activityType": "GENERIC",
            "activeKilocalories": 2,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630998000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61370df0-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 810,
            "startTimeInSeconds": 1630998000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61371174-1",
            "activityType": "RUNNING",
            "activeKilocalories": 2,
            "steps": 151,
            "distanceInMeters": 161.27,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1630998900,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.2068965,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 4.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61371174-6",
            "activityType": "WALKING",
            "activeKilocalories": 17,
            "steps": 671,
            "distanceInMeters": 477.75,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 405,
            "startTimeInSeconds": 1630998900,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.7790549,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.7037037037037037,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61371174-0",
            "activityType": "GENERIC",
            "activeKilocalories": 6,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1630998900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61371174-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 435,
            "startTimeInSeconds": 1630998900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613714f8-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.01,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1630999800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6137187c-6",
            "activityType": "WALKING",
            "activeKilocalories": 6,
            "steps": 406,
            "distanceInMeters": 289.07,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 360,
            "startTimeInSeconds": 1631000700,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.1027155,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.6666666666666667,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-6137187c-0",
            "activityType": "GENERIC",
            "activeKilocalories": 2,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631000700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-6137187c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 540,
            "startTimeInSeconds": 1631000700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61371c00-6",
            "activityType": "WALKING",
            "activeKilocalories": 2,
            "steps": 102,
            "distanceInMeters": 72.63,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1631001600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.7351437,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.3333333333333335,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61371c00-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631001600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61371c00-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1631001600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-61371f84-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631002500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61372308-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 42,
            "distanceInMeters": 29.9,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1631003400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61372308-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1631003400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-6137268c-6",
            "activityType": "WALKING",
            "activeKilocalories": 1,
            "steps": 108,
            "distanceInMeters": 76.9,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 315,
            "startTimeInSeconds": 1631004300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.210041,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.5714285714285716,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-6137268c-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 585,
            "startTimeInSeconds": 1631004300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-61372a10-6",
            "activityType": "WALKING",
            "activeKilocalories": 7,
            "steps": 161,
            "distanceInMeters": 114.63,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 420,
            "startTimeInSeconds": 1631005200,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.1027155,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.0,
            "maxMotionIntensity": 1.0
        },
        {
            "summaryId": "x34f8618-61372a10-0",
            "activityType": "GENERIC",
            "activeKilocalories": 4,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631005200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61372a10-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1631005200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 7.0
        },
        {
            "summaryId": "x34f8618-61372d94-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 142,
            "distanceInMeters": 101.1,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 175,
            "startTimeInSeconds": 1631006100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.1714285714285713,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61372d94-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631006100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61372d94-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 725,
            "startTimeInSeconds": 1631006100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-61373118-6",
            "activityType": "WALKING",
            "activeKilocalories": 15,
            "steps": 406,
            "distanceInMeters": 289.07,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 565,
            "startTimeInSeconds": 1631007000,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.756538,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.5132743362831858,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61373118-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 335,
            "startTimeInSeconds": 1631007000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 7.0
        },
        {
            "summaryId": "x34f8618-6137349c-1",
            "activityType": "RUNNING",
            "activeKilocalories": 34,
            "steps": 792,
            "distanceInMeters": 429.34,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 476,
            "startTimeInSeconds": 1631007900,
            "startTimeOffsetInSeconds": 28800,
            "met": 5.7259235,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 2.495798319327731,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6137349c-6",
            "activityType": "WALKING",
            "activeKilocalories": 18,
            "steps": 318,
            "distanceInMeters": 666.07,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 360,
            "startTimeInSeconds": 1631007900,
            "startTimeOffsetInSeconds": 28800,
            "met": 4.308146,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.6666666666666667,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-6137349c-0",
            "activityType": "GENERIC",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631007900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61373820-1",
            "activityType": "RUNNING",
            "activeKilocalories": 44,
            "steps": 792,
            "distanceInMeters": 581.13,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 419,
            "startTimeInSeconds": 1631008800,
            "startTimeOffsetInSeconds": 28800,
            "met": 7.947897,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 2.5704057279236276,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61373820-6",
            "activityType": "WALKING",
            "activeKilocalories": 14,
            "steps": 118,
            "distanceInMeters": 22.81,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1631008800,
            "startTimeOffsetInSeconds": 28800,
            "met": 6.146005,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 0.6666666666666666,
            "maxMotionIntensity": 1.0
        },
        {
            "summaryId": "x34f8618-61373820-0",
            "activityType": "GENERIC",
            "activeKilocalories": 13,
            "steps": 0,
            "distanceInMeters": 32.81,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631008800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61373820-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 1,
            "steps": 0,
            "distanceInMeters": 7.7,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 301,
            "startTimeInSeconds": 1631008800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.2198104,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61373ba4-1",
            "activityType": "RUNNING",
            "activeKilocalories": 21,
            "steps": 431,
            "distanceInMeters": 291.2,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 240,
            "startTimeInSeconds": 1631009700,
            "startTimeOffsetInSeconds": 28800,
            "met": 6.79075,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 2.5,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61373ba4-6",
            "activityType": "WALKING",
            "activeKilocalories": 10,
            "steps": 128,
            "distanceInMeters": 62.5,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 240,
            "startTimeInSeconds": 1631009700,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.7575002,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61373ba4-0",
            "activityType": "GENERIC",
            "activeKilocalories": 23,
            "steps": 0,
            "distanceInMeters": 13.49,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631009700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61373f28-6",
            "activityType": "WALKING",
            "activeKilocalories": 10,
            "steps": 358,
            "distanceInMeters": 254.9,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 420,
            "startTimeInSeconds": 1631010600,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.5757143,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.4285714285714284,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61373f28-0",
            "activityType": "GENERIC",
            "activeKilocalories": 5,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631010600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61373f28-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1631010600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-613742ac-6",
            "activityType": "WALKING",
            "activeKilocalories": 2,
            "steps": 82,
            "distanceInMeters": 58.38,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1631011500,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.1030002,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-613742ac-0",
            "activityType": "GENERIC",
            "activeKilocalories": 5,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631011500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613742ac-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1631011500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61374630-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 76,
            "distanceInMeters": 54.11,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1631012400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61374630-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1631012400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613749b4-6",
            "activityType": "WALKING",
            "activeKilocalories": 9,
            "steps": 280,
            "distanceInMeters": 199.36,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 300,
            "startTimeInSeconds": 1631013300,
            "startTimeOffsetInSeconds": 28800,
            "met": 2.9854,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613749b4-0",
            "activityType": "GENERIC",
            "activeKilocalories": 2,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631013300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613749b4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 600,
            "startTimeInSeconds": 1631013300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61374d38-1",
            "activityType": "RUNNING",
            "activeKilocalories": 7,
            "steps": 83,
            "distanceInMeters": 88.64,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1631014200,
            "startTimeOffsetInSeconds": 28800,
            "met": 4.8605,
            "intensity": "HIGHLY_ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61374d38-6",
            "activityType": "WALKING",
            "activeKilocalories": 12,
            "steps": 170,
            "distanceInMeters": 121.04,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 300,
            "startTimeInSeconds": 1631014200,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.6472,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61374d38-0",
            "activityType": "GENERIC",
            "activeKilocalories": 8,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631014200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61374d38-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 480,
            "startTimeInSeconds": 1631014200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613750bc-6",
            "activityType": "WALKING",
            "activeKilocalories": 11,
            "steps": 25,
            "distanceInMeters": 17.8,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1631015100,
            "startTimeOffsetInSeconds": 28800,
            "met": 5.0458603,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 1.0,
            "maxMotionIntensity": 1.0
        },
        {
            "summaryId": "x34f8618-613750bc-0",
            "activityType": "GENERIC",
            "activeKilocalories": 5,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631015100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613750bc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.02,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1631015100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61375440-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631016000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613757c4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631016900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61375b48-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631017800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61375ecc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631018700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61376250-6",
            "activityType": "WALKING",
            "activeKilocalories": 6,
            "steps": 104,
            "distanceInMeters": 74.05,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 180,
            "startTimeInSeconds": 1631019600,
            "startTimeOffsetInSeconds": 28800,
            "met": 3.206833,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-61376250-0",
            "activityType": "GENERIC",
            "activeKilocalories": 11,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 0,
            "startTimeInSeconds": 1631019600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61376250-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 720,
            "startTimeInSeconds": 1631019600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 6.0
        },
        {
            "summaryId": "x34f8618-613765d4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631020500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61376958-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 10,
            "distanceInMeters": 7.12,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 60,
            "startTimeInSeconds": 1631021400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 2.0,
            "maxMotionIntensity": 2.0
        },
        {
            "summaryId": "x34f8618-61376958-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 840,
            "startTimeInSeconds": 1631021400,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 5.0
        },
        {
            "summaryId": "x34f8618-61376cdc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631022300,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61377060-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631023200,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613773e4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631024100,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-61377768-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631025000,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61377aec-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631025900,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61377e70-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631026800,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        },
        {
            "summaryId": "x34f8618-613781f4-6",
            "activityType": "WALKING",
            "activeKilocalories": 0,
            "steps": 15,
            "distanceInMeters": 10.68,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 120,
            "startTimeInSeconds": 1631027700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "ACTIVE",
            "meanMotionIntensity": 3.0,
            "maxMotionIntensity": 3.0
        },
        {
            "summaryId": "x34f8618-613781f4-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 780,
            "startTimeInSeconds": 1631027700,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-61378578-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631028600,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 4.0
        },
        {
            "summaryId": "x34f8618-613788fc-8",
            "activityType": "SEDENTARY",
            "activeKilocalories": 0,
            "steps": 0,
            "distanceInMeters": 0.0,
            "durationInSeconds": 900,
            "activeTimeInSeconds": 900,
            "startTimeInSeconds": 1631029500,
            "startTimeOffsetInSeconds": 28800,
            "met": 1.0,
            "intensity": "SEDENTARY",
            "meanMotionIntensity": 0.0,
            "maxMotionIntensity": 0.0
        }
    ];
var res = stepSum.map(sumAll => sumAll.steps).reduce((acc, sumAll) => sumAll + acc);
console.log(res)




